[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
camera_network = "Hx5JaUCZXQqvcYzTcdgm9ZE3sqhMWqwAhNXZBrzWm45S"

[programs.devnet]
camera_network = "Hx5JaUCZXQqvcYzTcdgm9ZE3sqhMWqwAhNXZBrzWm45S"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./test-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
camera-network = "node scripts/camera-network-client.js"
face-test = "node scripts/face-recognition-test.js"
face-checkin = "node scripts/face-recognition-checkin.js"

[test]
startup_wait = 10000
