[toolchain]

[features]
seeds = true
skip-lint = false

[programs.devnet]
camera_network = "E67WTa1NpFVoapXwYYQmXzru3pyhaN9Kj3wPdZEyyZsL"

[programs.localnet]
camera_network = "E67WTa1NpFVoapXwYYQmXzru3pyhaN9Kj3wPdZEyyZsL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "target/deploy/camera_network-authority.json"

[scripts]
camera-network = "node scripts/camera-network-client.js"
face-checkin = "node scripts/face-recognition-checkin.js"
face-test = "node scripts/face-recognition-test.js"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false
